services:
  - type: web
    name: weather-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: your_mongodb_connection_string_here

  - type: web
    name: weather-frontend
    env: static
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
