services:
  - type: web
    name: weather-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://01fe22bcs133:01fe22bcs133@cluster0.3tajzbe.mongodb.net/weatherapp?retryWrites=true&w=majority&appName=Cluster0

  - type: web
    name: weather-frontend
    env: static
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
